  name: four-carrots App Android Release

  on:
    push:
      branches: [ "ktkdgh" ]
    pull_request:
      branches: [ "ktkdgh" ]

  jobs:
    flutter_test:
      name: Code analysis and testing
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Set up Flutter
          uses: subosito/flutter-action@v1.4.0
          with:
            channel: 'stable'
        - name: Get pub dependencies
          run: flutter pub get
        - name: Flutter analyze
          run: flutter analyze
        - name: Flutter test
          run: flutter test

#    android:
#      name: Android CI/CD
#      needs: flutter_test
#      runs-on: ubuntu-latest
#      steps:
#        -